providers = ["php", "node"]

[phases.setup]
commands = [
  "curl -sS https://getcomposer.org/installer | php",
  "mv composer.phar /usr/local/bin/composer"
]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
command = "php artisan serve --host 0.0.0.0 --port $PORT"
